networks:
  flickcrit-network:
    name: flickcrit-network
    labels:
      env: "development"
      project: "flickcrit"

volumes:
  db_postgres:

services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      retries: 20
      start_period: 20s
      timeout: 10s

    networks:
      - default
      - flickcrit-network

    ports:
      - "5432:5432"

    volumes:
      - db_postgres:/var/lib/postgresql/data



