{
 "title": "JVM SpringBoot3",
 "description": "JVM & Spring Boot 3 Monitoring ",
 "tags": [
  "JVM",
  "Spring Boot"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "mempool",
    "label": "mem pool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}, pool)"
    }
   },
   {
    "name": "memarea",
    "label": "mem area",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}, area)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\",pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\",pod=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\",pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\",pod=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "description": "JAVA版本号",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "description": "Java虚拟机可用的处理器数量",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "system_cpu_usage{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} * 100",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} * 100",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{ namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Info",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", status=~\"2..\"}[1m]))",
     "legendFormat": "HTTP - 200"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[15m])",
       "legendFormat": "process-15m"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "GC Pressure",
     "type": "timeseries",
     "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
       "legendFormat": "CPU time spent on GC"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "increase(logback_events_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_files_open_files{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])/rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m])",
       "legendFormat": "delta-1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_buffer_pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "repeat": "jvm_buffer_pool",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "capacity"
      },
      {
       "expr": "jvm_buffer_count_buffers{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "buffers"
      }
     ]
    }
   ]
  }
 ]
}