apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus_main_ds
    editable: true
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: passw0rd

