name: Project Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Run Integration Tests
        run: ./gradlew integrationTest --info

      - name: Build Test Report
        run: ./gradlew jacocoMergedReport

      - name: Generate JaCoCo Badge
        if: github.ref == 'refs/heads/main'
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.csv

      - name: Bump the Badge
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: '[ci] bump coverage badge'
          add: '*.svg'